import Foundation

public enum UTF8Arrays {
    public static let whitespace = " ".utf8Array
    public static let selfClosingTagEnd = " />".utf8Array
    public static let endTagStart = "</".utf8Array
    public static let tagStart = "<".utf8Array
    public static let tagEnd = ">".utf8Array
    public static let attributeEqualsQuoteMark = "=\"".utf8Array
    public static let quoteMark = "\"".utf8Array
    public static let html = "html".utf8Array
    public static let head = "head".utf8Array
    public static let meta = "meta".utf8Array
    public static let body = "body".utf8Array
    public static let a = "a".utf8Array
    public static let p = "p".utf8Array
    public static let li = "li".utf8Array
    public static let span = "span".utf8Array
    public static let img = "img".utf8Array
    public static let action = "action".utf8Array
    public static let prompt = "prompt".utf8Array
    public static let comment = "comment".utf8Array
    public static let hashRoot = "#root".utf8Array
    public static let ruby = "ruby".utf8Array
    public static let rb = "rb".utf8Array
    public static let rp = "rp".utf8Array
    public static let rt = "rt".utf8Array
    public static let rtc = "rtc".utf8Array
    public static let page = "page".utf8Array
    public static let table = "table".utf8Array
    public static let tbody = "tbody".utf8Array
    public static let th = "th".utf8Array
    public static let tr = "tr".utf8Array
    public static let td = "td".utf8Array
    public static let thead = "thead".utf8Array
    public static let tfoot = "tfoot".utf8Array
    public static let optgroup = "optgroup".utf8Array
    public static let select = "select".utf8Array
    public static let form = "form".utf8Array
    public static let plaintext = "plaintext".utf8Array
    public static let button = "button".utf8Array
    public static let image = "image".utf8Array
    public static let nobr = "nobr".utf8Array
    public static let input = "input".utf8Array
    public static let type = "type".utf8Array
    public static let hidden = "hidden".utf8Array
    public static let caption = "caption".utf8Array
    public static let hr = "hr".utf8Array
    public static let svg = "svg".utf8Array
    public static let isindex = "isindex".utf8Array
    public static let label = "label".utf8Array
    public static let xmp = "xmp".utf8Array
    public static let textarea = "textarea".utf8Array
    public static let iframe = "iframe".utf8Array
    public static let noembed = "noembed".utf8Array
    public static let option = "option".utf8Array
    public static let math = "math".utf8Array
    public static let sarcasm = "sarcasm".utf8Array // Huh
    public static let name = "name".utf8Array
    public static let col = "col".utf8Array
    public static let colgroup = "colgroup".utf8Array
    public static let frame = "frame".utf8Array
    public static let base = "base".utf8Array
    public static let href = "href".utf8Array
    public static let noscript = "noscript".utf8Array
    public static let noframes = "noframes".utf8Array
    public static let style = "style".utf8Array
    public static let title = "title".utf8Array
    public static let script = "script".utf8Array
    public static let br = "br".utf8Array
    public static let frameset = "frameset".utf8Array
    public static let blobColon = "blob:".utf8Array
    }
