name: macOS Swift



on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "fix/**" ]

jobs:
  build:
    name: Swift on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-15]
        
    runs-on: ${{ matrix.os }}

    steps:
    - name: Print Swift version
      run: swift --version
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Build Xcode framework
      run: xcodebuild -project SwiftSoup.xcodeproj -target SwiftSoup -configuration Release -sdk macosx CODE_SIGNING_ALLOWED=NO build
